name: Astro CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Dependency restore
      id: cache-restore
      uses: actions/cache@v4
      with:
        path: node_modules
        key: js-depend-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build website
      run: npm run build --if-present
      env: 
        FM_CLIENT_WEBSHOP_API_URL: ${{ vars.FM_CLIENT_WEBSHOP_API_URL }}
        FM_WEBSOCKET_URL: ${{ vars.FM_WEBSOCKET_URL }}
        PUBLIC_FM_PUBLIC_IMAGE_URL_PREFIX: ${{ vars.PUBLIC_FM_PUBLIC_IMAGE_URL_PREFIX }}
        PUBLIC_FM_COMPANY_NAME_SHORT: ${{ vars.PUBLIC_FM_COMPANY_NAME_SHORT }}
        PUBLIC_FM_COMPANY_NAME_FULL: ${{ vars.PUBLIC_FM_COMPANY_NAME_FULL }}
        PUBLIC_FM_TURNSTILE_SITEKEY: ${{ vars.PUBLIC_FM_TURNSTILE_SITEKEY }}
        PUBLIC_FM_COMPANY_NUMBER: ${{ vars.PUBLIC_FM_COMPANY_NUMBER }}
        PUBLIC_FM_DELIVERY_PROOF_IMAGE_URL_PREFIX: ${{ vars.PUBLIC_FM_DELIVERY_PROOF_IMAGE_URL_PREFIX }}
        PUBLIC_FM_HEADER_CAROUSEL_OFF_COOKIE_KEY: ${{ vars.PUBLIC_FM_HEADER_CAROUSEL_OFF_COOKIE_KEY }}
        PUBLIC_FM_CLIENT_WEBSHOP_REVOLUT_MODE: ${{ vars.PUBLIC_FM_CLIENT_WEBSHOP_REVOLUT_MODE }}
        PUBLIC_FM_ACCEPT_MEMBERSHIP: ${{ vars.PUBLIC_FM_ACCEPT_MEMBERSHIP }}
        FM_IS_ONLINE: ${{ vars.FM_IS_ONLINE }}
    - name: Reload PM2 process
      run: pm2 reload client-webshop